# Generated by Django 4.2.7 on 2023-12-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_auction_processed_alter_auction_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="auction", name="processed",),
    ]
